Feature/integrate helm solver
e2nIEE/pandapower pull request #2067
Opened 2023-06-06 18:33 UTC by vogt31337

Hi,

I've created a PR which enables the use of the [HELM](https://en.wikipedia.org/wiki/Holomorphic_Embedding_Load-flow_method) method for pandapower. For this to function HELMPy needs to be installed. At the moment a modified Version must be used (this one here [HELMPy](https://github.com/vogt31337/HELMpy)), this version returns more values, for example if the method did converge and how many pade approximations needed to be done to reach the target accuracy.

BR

2024-03-26 12:36 UTC, rbolgaryn commented
I think there should be more tests for this implementation

2024-03-26 12:37 UTC, rbolgaryn commented
Furthermore, documentation and CHANGELOG should be extended.

2024-03-26 12:37 UTC, rbolgaryn requested changes
see comments above

2024-03-28 10:10 UTC, vogt31337 commented
still some bugs, for some networks results match, for others results don't match. I'm not sure why atm. Will investigate further.

2026-07-02 08:45 UTC, KS-HTK requested changes

2026-07-02 08:45 UTC, KS-HTK commented on doc/powerflow/ac.rst
> +- "helm" holomorphic embedded loadflow method (Copyright (C) 2019 Tulio Molina tuliojose8@gmail.com and Juan José Ortega juanjoseop10@gmail.com)
Where did this Copyright note come from, I am not sure it is a good idea to include the emails directly in a scanable documentation. If they did this in there Copyright note it might be fine, but a better approach would be to link to the source of the implementation.

2026-07-02 08:45 UTC, KS-HTK commented on doc/powerflow/ac.rst
> +All of these algorithm provide pro and cons, the user can select an algorithm via :code:`runpp(algorithm="nr", ...)`
the algorithms do not provide pro and cons, they have them… What they provide is the output.

I think a better formulation would be "An algorithm might be better suited for a specific use case. The User …"

2026-07-02 08:45 UTC, KS-HTK commented on pandapower/test/loadflow/test_runpp_helm.py
> +# -*- coding: utf-8 -*-
We are not programming in python 2. Please do not add a coding header for python 3 since utf-8 is default for any python 3 .py file.

> If no encoding declaration is found, the default encoding is UTF-8. If the implicit or explicit encoding of a file is UTF-8, an initial UTF-8 byte-order mark (b'\xef\xbb\xbf') is ignored rather than being a syntax error.

https://docs.python.org/3/reference/lexical_analysis.html#encoding-declarations

2026-07-02 08:45 UTC, KS-HTK commented on pandapower/pf/run_helmpy_pf.py
> +from time import perf_counter
File is missing copyright header.

2026-07-02 09:24 UTC, vogt31337 commented on doc/powerflow/ac.rst
> +- "helm" holomorphic embedded loadflow method (Copyright (C) 2019 Tulio Molina tuliojose8@gmail.com and Juan José Ortega juanjoseop10@gmail.com)
It is directly from the authors github repo, see helmpy.

2026-07-02 09:25 UTC, vogt31337 commented on doc/powerflow/ac.rst
> +All of these algorithm provide pro and cons, the user can select an algorithm via :code:`runpp(algorithm="nr", ...)`
done.

2026-07-02 09:26 UTC, vogt31337 commented on pandapower/test/loadflow/test_runpp_helm.py
> +# -*- coding: utf-8 -*-
removed.

2026-07-02 09:26 UTC, vogt31337 commented on pandapower/pf/run_helmpy_pf.py
> +from time import perf_counter
added.

2026-07-02 09:35 UTC, KS-HTK submitted a review, later dismissed

2026-07-02 12:57 UTC, KS-HTK approved these changes

2026-07-02 12:59 UTC, merged