consider all oos elements if required in network x graph
e2nIEE/pandapower pull request #2388
Opened 2024-09-02 13:31 UTC by SimonRubenDrauz

2024-09-05 06:45 UTC, pawellytaev requested changes
Please update the changelog and the docstring for the include_out_of_service parameter

2025-01-03 10:03 UTC, vogt31337 commented
@SimonRubenDrauz, please add a changelog entry.

2025-01-08 10:10 UTC, SimonRubenDrauz commented
Done!

2025-01-08 12:04 UTC, pawellytaev approved these changes

2025-01-08 12:04 UTC, merged