Feature/ucte converter
e2nIEE/pandapower pull request #2498
Opened 2024-12-18 16:22 UTC by SteffenMeinecke

I think, it should be complete. Further refactoring can be done if there is ever time for it, as always.

The merge should be done as squash merge, I propose.

2025-01-03 09:47 UTC, vogt31337 requested changes
See comments.

2025-01-03 09:47 UTC, vogt31337 commented on doc/pics/e2n.png
Why increase the size of this image? +530%?
Keep traffic in mind & slow connection.

2025-01-03 09:47 UTC, vogt31337 commented on doc/pics/e2n.png
Also please do not change things unrelated to the original intent of the PR.

2025-01-03 09:47 UTC, vogt31337 commented on pandapower/std_types.py
Why did you change the std_type and the corresponding test? Does this need to be changed for a new converter? If not, please extract this to it's own PR.

2025-01-03 09:47 UTC, vogt31337 commented on pandapower/test/api/test_std_types.py
Why did you change the std_type and the corresponding test? Does this need to be changed for a new converter? If not, please extract this to it's own PR.

2025-01-03 09:47 UTC, vogt31337 commented on tutorials/new_optimization_model_pandamodels.ipynb
Again unrelated to original PR intent. Please check and push as seperate PR.

2025-01-03 09:47 UTC, vogt31337 commented on doc/converter/ucte.rst
If the test data is not created by you, please add a reference from where the test data originated in this rst.

2025-01-06 11:27 UTC, SteffenMeinecke commented on pandapower/std_types.py
yes, it is applied in this PR and was in the meantime independently merged by https://github.com/e2nIEE/pandapower/pull/2479.

2025-01-06 11:43 UTC, SteffenMeinecke commented on doc/pics/e2n.png
> Why increase the size of this image? +530%?
Sorry, I provided the original/official new e2n logo. I now provided another png file, smaller in memory space.

> Also please do not change things unrelated to the original intent of the PR.
In general: absolutely, I agree!
Here, however, all other contents --- seen individually --- are really small fixes and would cause so much overhead work load which I cannot provide at the moment.

2025-01-06 11:46 UTC, SteffenMeinecke commented on pandapower/test/api/test_std_types.py
as above: changes in `std_types.py` are needed partly. Additional tests were added as small missing tests (could be extracted to its own PR if enough time.

2025-01-06 11:47 UTC, SteffenMeinecke commented on tutorials/new_optimization_model_pandamodels.ipynb
I agree, but I disagree on opening an individual PR for removing just an empty ipynb.

2025-01-06 12:01 UTC, SteffenMeinecke commented on doc/converter/ucte.rst
Good idea -> solved by https://github.com/e2nIEE/pandapower/pull/2498/commits/bf5f377ee016a3fae8afe1357438c2d62a78363c

2025-01-06 12:04 UTC, SteffenMeinecke commented
> See comments.

Thanks, @vogt31337 for your review and ideas!

2025-01-06 12:09 UTC, SteffenMeinecke commented
@mrifraunhofer can you also have a look?

2025-01-30 16:44 UTC, pawellytaev approved these changes

2025-01-30 16:44 UTC, pawellytaev approved these changes
looks fine from my side, thanks :)

2025-01-31 07:54 UTC, merged